
export default function env() {

    const { NODE_ENV, PORT, CLIENT_URL, JWT_SECRET, MONGO_DB_URI, CLOUDINARY_CLOUD_NAME, CLOUDINARY_UPLOAD_PRESET, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET } = process.env;

    return {
        NODE_ENV,
        PORT,
        CLIENT_URL,
        JWT_SECRET,
        MONGO_DB_URI,
        CLOUDINARY_CLOUD_NAME,
        CLOUDINARY_UPLOAD_PRESET,
        CLOUDINARY_API_KEY,
        CLOUDINARY_API_SECRET
    }
}

