name: Chat App Deploy on EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            server/package-lock.json
            client/package-lock.json

      # ------------------------------
      # REDIS SETUP
      # ------------------------------
      - name: Install Redis
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-server

      - name: Start Redis service
        run: |
          sudo systemctl start redis-server
          sudo systemctl enable redis-server

      - name: Test Redis connection
        run: |
          redis-cli ping

      # ------------------------------
      # BACKEND SETUP
      # ------------------------------
      - name: Install backend dependencies
        working-directory: ./server
        run: npm install

      - name: Create backend .env file
        working-directory: ./server
        run: |
          touch .env
          echo "${{ secrets.PROD_BACKEND_ENV }}" > .env

      - name: Install PM2 globally
        run: npm install -g pm2

      - name: Start backend with PM2
        working-directory: ./server
        run: |
          pm2 delete chat-app-be || true
          pm2 start server.js --name chat-app-be --time
          pm2 save
          pm2 startup

      # ------------------------------
      # FRONTEND SETUP
      # ------------------------------
      - name: Clean npm cache & remove existing dependencies
        working-directory: ./client
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force

      - name: Install frontend dependencies
        working-directory: ./client
        run: npm install

      - name: Create frontend .env file
        working-directory: ./client
        run: |
          touch .env
          echo "${{ secrets.PROD_FRONTEND_ENV }}" > .env

      - name: Build frontend
        working-directory: ./client
        run: npm run build

      - name: Deploy frontend to Nginx
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r ./client/dist/* /var/www/html/
          sudo chown -R www-data:www-data /var/www/html/
          sudo chmod -R 755 /var/www/html/

      # ------------------------------
      # FINAL CHECKS
      # ------------------------------
      - name: Check PM2 status
        run: pm2 status

      - name: Check Redis status
        run: sudo systemctl status redis-server

      - name: Check Nginx status
        run: sudo systemctl status nginx
